version: "3.3"
services:
  rmorthanc:
    image: osimis/orthanc
    container_name: rmorthanc
    ports:
      - "4242:4242"
      - "8042:8042"
    volumes:
      - /opt/report-med/storage:/var/lib/orthanc/db
    environment:
      ORTHANC__NAME: "REPORTMED"
      ORTHANC__DICOM_AET: "REPORTMED"
      VERBOSE_ENABLED: "true"
      VERBOSE_STARTUP: "true"
      TRACE_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      ORTHANC__ORTHANC_EXPLORER_2__UI_OPTIONS__ENABLE_OPEN_IN_OHIF_VIEWER: "true"
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      CONNECTIVITY_CHECKS_PLUGIN_ENABLED: "true"
      TRANSFERS_PLUGIN_ENABLED: "true"
      WORKLISTS_PLUGIN_ENABLED:  "true"
      ORTHANC__DICOM_MODALITIES: |
        {
          "REPORTMED2": ["REPORTMED2", "192.168.1.2", 4242]
        }
    secrets:
      - report-med.secret.json
    networks:
      - rm-network
    restart: always

secrets:
  report-med.secret.json:
    file: report-med.secret.json
    
networks:
  rm-network:
    name: rm-network
    driver: bridge