services:
  traefik:
    image: traefik
    container_name: traefik
    environment:
      - TZ=America/Sao_Paulo
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --api
      - --log.level=DEBUG
      - --certificatesresolvers.letsencrypt.acme.email=admin@areport-med.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    # labels:
      # # Dashboard
      # - "traefik.http.routers.traefik.rule=Host(`dashboard.report-med.com`)"
      # - "traefik.http.routers.traefik.service=api@internal"
      # - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.traefik.entrypoints=websecure"
      # - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      # - "traefik.http.routers.http-catchall.entrypoints=web"
      # - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  # helloworld:
    # container_name: helloworld
    # image: crccheck/hello-world
    # ports:
      # - 8000:8000
    # restart: always
    # networks:
      # - web
    # labels:
      # - "traefik.http.routers.app1.rule=Host(`api-ws.report-med.com`)"
      # - "traefik.http.routers.app1.entrypoints=websecure"
      # - "traefik.http.routers.app1.tls=true"
      # - "traefik.http.routers.app1.tls.certresolver=letsencrypt"
      # - traefik.port=8000
