version: "3.3"
services:
  rmftp:
    image: stilliard/pure-ftpd
    container_name: rmftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/opt/report-med/ftp:/home/ftp/"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: ftp
      FTP_USER_PASS: ftp
      FTP_USER_HOME: /home/ftp
    networks:
      - rm-network
    restart: always

networks:
  rm-network:
    name: rm-network
    driver: bridge