version: "3.3"
services:
  rmdatabase:
    image: mysql
    container_name: rmdatabase
    ports:
      - "3306:3306"
    command:
      [
        mysqld,
        --default-authentication-plugin=mysql_native_password,
        --log-bin-trust-function-creators=1,
      ]
    volumes:
      - /opt/report-med/mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: Ls001008**++
      MYSQL_ROOT_PASSWORD: Ls001008**++
    networks:
      - rm-network
    restart: always
    
networks:
  rm-network:
    name: rm-network
    driver: bridge