services:
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/report-med/portainer:/data"
    networks:
      - rm-network
    restart: always

networks:
  rm-network:
    name: rm-network
    driver: bridge
